language: node_js
node_js: 
  - "stable"
services:
  - "postgresql"
env:
  - NODE_ENV=test
cache:
  directories:
    - "node_modules"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - psql -c "CREATE USER jaachimma WITH PASSWORD 'password';" -U postgres
script: npm run test
after_success: npm run coverage